### ISSUE TITLE
Wrong error message shown when prefixes are capitalised. Prefixes should be case-insensitive.

### ISSUE THREAD

**Issue by pongzers** [AY2021S1-CS2103T-T17-1/tp#95]
![image](https://user-images.githubusercontent.com/58703443/97114740-44319780-172d-11eb-91ee-bcb63b4efeab.png)

**Comment by zhaolingshan** [comment]
add m/CS2030 G/ gives "Names should only contain alphanumeric characters and spaces, and it should not be blank"
should be invalid command format

**Comment by zhaolingshan** [comment]
![Uploading Screenshot 2020-11-04 at 3.32.00 PM.png…]()

**Comment by zhaolingshan** [comment]
<img width="737" alt="Screenshot 2020-11-04 at 3 32 00 PM" src="https://user-images.githubusercontent.com/65531702/98082173-41fcd500-1eb3-11eb-890e-9231137b989c.png">
